1. What does Pandas stand for?

    # Stands for either:
        1. Panel Data and/or
        2. Python Data Analysis

2. What are the 2 collections used in Pandas?

    # Series and DataFrames

3. Name 4 things Pandas can do for us.

    # Pandas can perform five significant steps required for processing and analysis of data, irrespective of the origin of the data:
    # Perform 5 data analysis steps:
        1. load
        2. manipulate
        3. prepare
        4. model
        5. analyze
    

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

    # inplace = true

5. What is a CSV?

    # Comma Separated Value data file


6. When cleaning data what values do we not like in our data?

    # NULLS


In [12]:
import numpy as np

arrayA= np.array([2, 3, 2])

print(arrayA)

newShape = arrayA.reshape(3, -1)
print("\narrayA reshaped with (3,-1)\n", newShape)


[2 3 2]

arrayA reshaped with (3,-1)
 [[2]
 [3]
 [2]]


In [13]:
Array1 = np.linspace(0, 20, num=6)
print(Array1)


[ 0.  4.  8. 12. 16. 20.]


In [14]:
import copy

zArray = copy.deepcopy(Array1)

print(zArray)


[ 0.  4.  8. 12. 16. 20.]


In [16]:
Array2 = ([[25, 16]])
Array3 = ([[11, 2], [13, 4]])
Array4 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((Array2, Array3, Array4), axis=0)
print(newArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [18]:
sortedArray = np.sort(newArray)
print(sortedArray)


[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [26]:
a, b, c, d, e, f = newArray

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

    #Number 12 here is unclear, are we to use the "reshapedArray" from #7, or use the "sortedArray" from #11?  THere are more than 4 variables?


[25 16]
[11  2]
[13  4]
[ 7 81]
[5 6]
[11 12]


In [93]:
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis = 0)
print(comboArray)

comboArray = np.sort(comboArray)
print(comboArray)


[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [116]:
print(comboArray[2])

print(comboArray[3:])

print(comboArray[4:15])

print(comboArray[-6:24])

print(comboArray[:-10])

print(comboArray[16:27:2])

print(comboArray[::-5])


2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [1]:
import numpy as np
import pandas as pd

In [7]:
Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"])
Quantity = pd.Series([4,1,2,1])
Unit  = pd.Series(["cups","cup","large","can"])
print(Ingredients)
print(Quantity)
print(Unit)



0    Flour
1     Milk
2     Eggs
3     Spam
dtype: object
0    4
1    1
2    2
3    1
dtype: int64
0     cups
1      cup
2    large
3      can
dtype: object


In [8]:
df = pd.concat([Ingredients, Quantity, Unit], axis=1)
print(df)


       0  1      2
0  Flour  4   cups
1   Milk  1    cup
2   Eggs  2  large
3   Spam  1    can


In [86]:
Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"], name="Ingredients")
Quantity = pd.Series([4,1,2,1], name="Quantity")
Unit  = pd.Series(["cups","cup","large","can"], name="Unit")
df = pd.concat([Ingredients, Quantity, Unit], axis=1)
print(df)


  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [90]:

df = "Dinner"
print(Dinner.loc["Dinner"])


Ingredients    Spam
Quantity          1
Unit            can
Name: Dinner, dtype: object


In [20]:
Receipe = {
    "Ingredients": ["Flour","Milk","Eggs","Spam"],
    "Quantity": [4,1,2,1],
    "Unit": ["cups","cup","large","can"]
    }
  
Dinner = pd.DataFrame(Receipe)
Dinner

Dinner = pd.DataFrame(Receipe, index = ["Dinner1", "Dinner2", "Dinner3", "Dinner"])
Dinner

print(Dinner.loc["Dinner"])


Ingredients    Spam
Quantity          1
Unit            can
Name: Dinner, dtype: object


In [41]:
import pandas as pd

In [63]:
stuData = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj', ""],
    'Height': [5.1, 6.2, 5.1, 5.2, 0 ],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc', ""],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar', ""],
    'Age': [21, 23, 24, 21, 0],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot', ""],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket', ""]
    }

studentData = pd.DataFrame(stuData)
studentData

df=studentData
df


deserts = ["ice cream", "Cashew", "Fudge", "waffels", "Carrot Halwa"]
df = df.assign(Deserts=deserts)
print("\nDF with assigned column added\n", df)


DF with assigned column added
       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
4              0.0                           0                               

        Deserts  
0     ice cream  
1        Cashew  
2         Fudge  
3       waffels  
4  Carrot Halwa  


In [64]:
df.sort_values(by = ["Name", "address"], inplace = True)
df


Name  Height Qualification  address  Age        Pets           sport  \
4              0.0                           0                               
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
4  Carrot Halwa  
3       waffels  
2         Fudge  
0     ice cream  
1        Cashew

In [66]:
import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')
df =pd.read_csv("cows_and_goats.csv")
df



Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19

In [83]:
import pandas as pd

Vegetables = pd.DataFrame({'Carrots': [44, 99], 'Turnips': [36, 19]}, index=['Year1', 'Year 2'])
Vegetables

Vegetables.to_csv("Vegetables.csv")

df =pd.read_csv("Vegetables.csv")
df

Vegetables.to_csv("vegETABLES", sep="\t")

