1. What does Pandas stand for?

    # Stands for either:
        1. Panel Data and/or
        2. Python Data Analysis

2. What are the 2 collections used in Pandas?

    # Series and DataFrames

3. Name 4 things Pandas can do for us.

    # Pandas can perform five significant steps required for processing and analysis of data, irrespective of the origin of the data:
    # Perform 5 data analysis steps:
        1. load
        2. manipulate
        3. prepare
        4. model
        5. analyze
    

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

    # inplace = true

5. What is a CSV?

    # Comma Separated Value data file


6. When cleaning data what values do we not like in our data?

    # NULLS


In [12]:
import numpy as np

arrayA= np.array([2, 3, 2])

print(arrayA)

newShape = arrayA.reshape(3, -1)
print("\narrayA reshaped with (3,-1)\n", newShape)


[2 3 2]

arrayA reshaped with (3,-1)
 [[2]
 [3]
 [2]]


In [13]:
Array1 = np.linspace(0, 20, num=6)
print(Array1)


[ 0.  4.  8. 12. 16. 20.]


In [14]:
import copy

zArray = copy.deepcopy(Array1)

print(zArray)


[ 0.  4.  8. 12. 16. 20.]


In [16]:
Array2 = ([[25, 16]])
Array3 = ([[11, 2], [13, 4]])
Array4 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((Array2, Array3, Array4), axis=0)
print(newArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [18]:
sortedArray = np.sort(newArray)
print(sortedArray)


[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [26]:
a, b, c, d, e, f = newArray

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

    #Number 12 here is unclear, are we to use the "reshapedArray" from #7, or use the "sortedArray" from #11?  THere are more than 4 variables?


[25 16]
[11  2]
[13  4]
[ 7 81]
[5 6]
[11 12]


In [41]:
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three), axis = 0)
print(comboArray)

comboArray = np.sort(comboArray)
print(comboArray)


[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [63]:
print(comboArray[2])

print(comboArray[3:])

print(comboArray[4:15])

print(comboArray[18:24])

print(comboArray[])

print(comboArray[])

print(comboArray[])

2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
